In [1615]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Column Description

| **Column Name** | **Description**                                                                                           |
| --------------- | --------------------------------------------------------------------------------------------------------- |
| **Index**       | Unique serial number assigned to each property.                                                           |
| **Title**       | Short title or headline describing the property listing.                                                  |
| **Description** | Detailed textual description of the property and its features.                                            |
| **Amount**      | Total listed price of the property.                                                                       |
| **Price**       | Price per square foot of the property.                                                                    |
| **Location**    | City or locality where the property is located.                                                           |
| **Carpet Area** | Actual usable floor area inside the property, measured in square feet (sq ft) or square yards (sq yd).    |
| **Status**      | Indicates whether the property is ready for immediate occupancy or is under construction.                 |
| **Floor**       | Floor number on which the property is located.                                                            |
| **Transaction** | Indicates whether the property is a new property or a resale.                                             |
| **Furnishing**  | Furnishing status of the property (e.g., Furnished, Semi-Furnished, Unfurnished).                         |
| **Facing**      | Direction the property's main entrance or balcony faces (e.g., North, South, East, West).                 |
| **Overlooking** | Primary view from the property, such as a park, garden, pool, or main road.                               |
| **Society**     | Name of the residential society or apartment complex where the property is located.                       |
| **Bathroom**    | Total number of bathrooms in the property.                                                                |
| **Balcony**     | Total number of balconies available in the property.                                                      |
| **Car Parking** | Number of dedicated parking spaces available for vehicles.                                                |
| **Ownership**   | Type of legal ownership, such as Freehold or Cooperative Society.                                         |
| **Super Area**  | Total saleable area, including the carpet area, wall thickness, and a proportional share of common areas. |
| **Dimensions**  | Physical dimensions of the property (e.g., length × width).                                               |
| **Plot Area**   | Total land area occupied by the property.                                                                 |

In [1616]:
house_df = pd.read_csv('../datasets/house_prices.zip')
house_copy = house_df.copy()

In [1617]:
columns = house_copy.columns
columns = pd.Series(columns.str.split('(').str.get(0).str.strip().str.lower().str.split(' ')).apply(lambda x : '_'.join(x))
house_copy.columns = columns
columns
house_copy.drop('index', axis= 1, inplace= True)

# Data Cleaning

### Messy Data

- Extra index column is given.

- Two informations are in the same column Title which are number of bedrooms and location.

- The phrase `BHK Ready to Occupy Flat for Sale` is common in every value of the column Title.

- Description has 5 major informations number of bedrooms, precise area, price, commercials and whether it is furnished, semi-funished or unfurnished.

- Location has two informations total floors in buildings and on which floor flat is located.

- 63% of data is duplicated.

### Dirty Data

- Some column names are lower case and some are capitalize. `consisttency`

- Some of the values are same in Title and Description column. `uniqueness`

- Amount column has dtype string and inconsistent units. `inconsistency`

- Description, Price, Location, Status, facting, overlooking, society, balcony, car parking, ownership and has missing values. `completeness`

- Carpet Area and Super Area column has inconsitent units and missing values. `incosnistency` and `completeness`

- Dimensions and Plot Area has all values missing. `completeness`

- Bathroom and Balcony has dtype string instead of integer. `invalid`


#### Quality Dimensions Solution:
1. Uniqueness
2. Completeness
3. Tidiness
4. Validity
5. Accuracy 
6. Consistency

In [1618]:
house_copy.head()

,title,description,amount,price,location,carpet_area,status,floor,transaction,furnishing,facing,overlooking,society,bathroom,balcony,car_parking,ownership,super_area,dimensions,plot_area
0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [1619]:
house_copy.shape

(187531, 20)

In [1620]:
house_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 20 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   title        187531 non-null  str
 1   description  184508 non-null  str
 2   amount       187531 non-null  str
 3   price        169866 non-null  float64
 4   location     187531 non-null  str
 5   carpet_area  106858 non-null  str
 6   status       186916 non-null  str
 7   floor        180454 non-null  str
 8   transaction  187448 non-null  str
 9   furnishing   184634 non-null  str
 10  facing       117298 non-null  str
 11  overlooking  106095 non-null  str
 12  society      77853 non-null   str
 13  bathroom     186703 non-null  str
 14  balcony      138596 non-null  str
 15  car_parking  84174 non-null   str
 16  ownership    122014 non-null  str
 17  super_area   79846 non-null   str
 18  dimensions   0 non-null       float64
 19  plot_area    0 non-null       float64
dtypes: float64(3), str(17)
memory usage: 28.6 MB

In [1621]:
house_copy.describe()

              price  dimensions  plot_area
count  1.698660e+05         0.0        0.0
mean   7.583772e+03         NaN        NaN
std    2.724171e+04         NaN        NaN
min    0.000000e+00         NaN        NaN
25%    4.297000e+03         NaN        NaN
50%    6.034000e+03         NaN        NaN
75%    9.450000e+03         NaN        NaN
max    6.700000e+06         NaN        NaN

In [1622]:
house_copy.duplicated().sum()

np.int64(119339)

In [1623]:
house_copy.duplicated().sum() / len(house_copy) * 100

np.float64(63.63694535836741)

In [1624]:
location = house_copy['location'].value_counts()
location.index

Index(['new-delhi', 'bangalore', 'kolkata', 'gurgaon', 'ahmedabad',
       'hyderabad', 'chennai', 'jaipur', 'greater-noida', 'faridabad',
       'vadodara', 'surat', 'pune', 'thane', 'mumbai', 'visakhapatnam',
       'mohali', 'zirakpur', 'chandigarh', 'noida', 'goa', 'ranchi', 'bhiwadi',
       'kochi', 'dehradun', 'ghaziabad', 'lucknow', 'kanpur', 'patna',
       'guwahati', 'sonipat', 'coimbatore', 'navi-mumbai', 'nagpur',
       'jamshedpur', 'kalyan', 'vijayawada', 'palghar', 'raipur',
       'bhubaneswar', 'agra', 'aurangabad', 'mangalore', 'badlapur',
       'siliguri', 'panchkula', 'nashik', 'guntur', 'varanasi', 'thrissur',
       'trivandrum', 'allahabad', 'ernakulam', 'haridwar', 'mysore',
       'durgapur', 'gwalior', 'ludhiana', 'vapi', 'indore', 'bhopal',
       'jabalpur', 'trichy', 'udaipur', 'bhiwandi', 'rajahmundry', 'tirupati',
       'belgaum', 'jodhpur', 'kozhikode', 'satara', 'shimla', 'udupi',
       'vrindavan', 'ahmadnagar', 'madurai', 'navsari', 'nellore', 'palakkad',
       'pondicherry', 'solapur'],
      dtype='str', name='location')

In [1625]:
society = house_copy['society'].value_counts()
society

society
Hamdam Apartment              1648
Malibu Town                   1158
Shree Vardhman Victoria       1154
DLF Skycourt                  1153
Nebula Tower                   982
                              ...
Sushma Capital                   1
Sushma Chandigarh Infinium       1
Silver City Greens               1
Nirmaan Royale Empire            1
Jaivee Radha Enclave             1
Name: count, Length: 10376, dtype: int64

In [1626]:
house_copy['ownership'].value_counts()

ownership
Freehold                112229
Leasehold                 5285
Co-operative Society      3431
Power Of Attorney         1069
Name: count, dtype: int64

In [1627]:
house_copy.drop_duplicates(inplace= True)

In [1628]:
house_copy= house_copy.drop(columns= ['dimensions', 'plot_area'])

In [1629]:
house_copy.isna().sum()

title              0
description     2218
amount             0
price           5894
location           0
carpet_area    30117
status           299
floor           2615
transaction       78
furnishing      1290
facing         26800
overlooking    29535
society        38820
bathroom         471
balcony        19059
car_parking    39329
ownership      24928
super_area     38199
dtype: int64

In [1630]:
house_copy['title'] = house_copy['title'].str.replace('BHK Ready to Occupy Flat for sale ', '')
house_copy['title'] = house_copy['title'].str.replace(' in', '')
house_copy['bedrooms'] = house_copy['title'].str.split(pat= ' ', n= 1).str.get(0)
house_copy['title'] = house_copy['title'].str.split(pat= ' ', n= 1).str.get(1)

def my_logic(s1, s2):
    for title, society in zip(s1, s2):
        if title is not np.nan and society is not np.nan:
            title = title.replace(society, '')
        yield title

func = my_logic(house_copy['title'], house_copy['society'])

house_copy['locality'] = pd.Series([new for new in func])

house_copy[(house_copy['locality'].isna() == False) & (house_copy['society'].isna() == False)].shape[0] / len(house_copy)

0.08877874237447207

In [1631]:
house_copy['bedrooms'] = pd.to_numeric(house_copy['bedrooms'], errors= 'coerce')

In [1632]:
house_copy.isna().sum()

title              0
description     2218
amount             0
price           5894
location           0
carpet_area    30117
status           299
floor           2615
transaction       78
furnishing      1290
facing         26800
overlooking    29535
society        38820
bathroom         471
balcony        19059
car_parking    39329
ownership      24928
super_area     38199
bedrooms         361
locality       53585
dtype: int64

In [1633]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        68192 non-null  object
 1   description  65974 non-null  str
 2   amount       68192 non-null  str
 3   price        62298 non-null  float64
 4   location     68192 non-null  str
 5   carpet_area  38075 non-null  str
 6   status       67893 non-null  str
 7   floor        65577 non-null  str
 8   transaction  68114 non-null  str
 9   furnishing   66902 non-null  str
 10  facing       41392 non-null  str
 11  overlooking  38657 non-null  str
 12  society      29372 non-null  str
 13  bathroom     67721 non-null  str
 14  balcony      49133 non-null  str
 15  car_parking  28863 non-null  str
 16  ownership    43264 non-null  str
 17  super_area   29993 non-null  str
 18  bedrooms     67831 non-null  float64
 19  locality     14607 non-null  str
dtypes: float64(2), object(1), str(17)
memory usage: 10.9+ MB

In [1634]:
house_copy['amount'] = np.where((house_copy['amount'].str.contains('Call for Price')) | (house_copy['amount'].isna()), house_copy['description'].str.extract(r'(\d+\.?\d*\s*(?:Cr|Lac))', expand= False), house_copy['amount'])

In [1635]:
house_copy['figure'] = house_copy['amount'].str.split(' ').str.get(1).str.strip()
house_copy['amount'] = house_copy['amount'].str.split(' ').str.get(0).str.strip()
house_copy['amount'] = house_copy['amount'].astype('float64')
house_copy['amount'] = np.where(house_copy['figure'] == 'Cr', house_copy['amount'] * 100, house_copy['amount'])
print(house_copy[['figure', 'amount']])

       figure  amount
0         Lac    42.0
1         Lac    98.0
2          Cr   140.0
3         Lac    25.0
4          Cr   160.0
...       ...     ...
187526    Lac    63.0
187527    Lac    55.0
187528    Lac    76.0
187529    Lac    30.0
187530     Cr   118.0

[68192 rows x 2 columns]

In [1636]:
house_copy.drop(columns= ['figure', 'status'], inplace= True)

In [1637]:
house_copy[house_copy['super_area'].str.contains('sqyrd', na= False)]

,title,description,amount,price,location,carpet_area,floor,transaction,furnishing,facing,overlooking,society,bathroom,balcony,car_parking,ownership,super_area,bedrooms,locality
2626,Samruddhi Anushri Residency Gota,"This lovely 2 BHK Flat in Gota, Ahmedabad is u...",35.0,3889.0,ahmedabad,NaN,5 out of 7,Resale,Unfurnished,NaN,NaN,Samruddhi Anushri Residency,2,NaN,NaN,NaN,100 sqyrd,2.0,Chandkheda
2627,"Pruthvi Tower Jodhpur Village, Jodhpur",This attractive 3 BHK apartment can be found f...,88.0,6391.0,ahmedabad,NaN,9 out of 10,Resale,Semi-Furnished,NaN,NaN,Pruthvi Tower,2,NaN,NaN,NaN,153 sqyrd,3.0,"Jodhpur Village, Jodhpur"
2633,Bopal,This exquisite 2 BHK Flat is offered for sale ...,55.0,4701.0,ahmedabad,NaN,1 out of 10,New Property,Semi-Furnished,East,"Garden/Park, Main Road",NaN,2,1,"1 Covered,",Freehold,130 sqyrd,2.0,Prahlad Nagar
2647,Sahibaugh Ahmedabad,"Sahibaugh, Ahmedabad has an appealing 1 BHK fl...",27.0,4615.0,ahmedabad,NaN,3 out of 4,Resale,Semi-Furnished,NaN,Main Road,NaN,1,NaN,NaN,Co-operative Society,65 sqyrd,1.0,Aarohi Club Road
2654,Sanand,"This lovely 2 BHK Flat in Sanand, Ahmedabad is...",45.0,3226.0,ahmedabad,NaN,2 out of 5,Resale,Furnished,NaN,NaN,NaN,2,NaN,NaN,NaN,155 sqyrd,2.0,Maninagar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187013,Lohgarh,Up for immediate sale is a 4 BHK apartment in ...,52.0,3106.0,zirakpur,NaN,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,3,NaN,NaN,NaN,186 sqyrd,4.0,NaN
187186,"Dhakoli, Zirakpur Zirakpur",Discover this immaculate 3 BHK flat for sale a...,48.0,3556.0,zirakpur,NaN,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,3,NaN,NaN,NaN,150 sqyrd,3.0,NaN
187200,Green city,Creatively planned and constructed is a 3 BHK ...,40.0,3704.0,zirakpur,NaN,3 out of 4,Resale,Semi-Furnished,NaN,NaN,NaN,3,NaN,NaN,NaN,120 sqyrd,3.0,NaN
187309,"Ishmita homes, Kishanpura, Dhakoli Zirakpur",This beautiful 3 BHK Flat is available for sal...,40.0,3556.0,zirakpur,NaN,3 out of 3,Resale,Semi-Furnished,NaN,NaN,NaN,3,NaN,NaN,NaN,125 sqyrd,3.0,NaN
187437,Bollywood Esencia Gazipur,One can find this stunning 3 BHK flat for sale...,52.8,3259.0,zirakpur,NaN,2 out of 4,New Property,Semi-Furnished,East,Main Road,Bollywood Esencia,3,2,1 Covered,Freehold,180 sqyrd,3.0,NaN

In [1638]:
house_copy['carpet_unit']  =  house_copy['carpet_area'].str.split(' ').str.get(1)
house_copy['carpet_area'] = house_copy['carpet_area'].str.split(' ').str.get(0)
house_copy['super_unit']  =  house_copy['super_area'].str.split(' ').str.get(1)
house_copy['super_area'] = house_copy['super_area'].str.split(' ').str.get(0).str.strip()

In [1639]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        68192 non-null  object
 1   description  65974 non-null  str
 2   amount       67841 non-null  float64
 3   price        62298 non-null  float64
 4   location     68192 non-null  str
 5   carpet_area  38075 non-null  object
 6   floor        65577 non-null  str
 7   transaction  68114 non-null  str
 8   furnishing   66902 non-null  str
 9   facing       41392 non-null  str
 10  overlooking  38657 non-null  str
 11  society      29372 non-null  str
 12  bathroom     67721 non-null  str
 13  balcony      49133 non-null  str
 14  car_parking  28863 non-null  str
 15  ownership    43264 non-null  str
 16  super_area   29993 non-null  object
 17  bedrooms     67831 non-null  float64
 18  locality     14607 non-null  str
 19  carpet_unit  38075 non-null  object
 20  super_unit   29993 non-null  object
dtypes: float64(3), object(5), str(13)
memory usage: 11.4+ MB

In [1640]:
house_copy['carpet_area'] = house_copy['carpet_area'].astype('float64')
house_copy['super_area'] = pd.to_numeric(house_copy['super_area'], errors= 'coerce')

In [1641]:
house_copy.head()

,title,description,amount,price,location,carpet_area,floor,transaction,furnishing,facing,...,society,bathroom,balcony,car_parking,ownership,super_area,bedrooms,locality,carpet_unit,super_unit
0,Srushti Siddhi Mangal Murti Complex Bhiwandi,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42.0,6000.0,thane,500.0,10 out of 11,Resale,Unfurnished,NaN,...,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,1.0,Bhiwandi,sqft,NaN
1,Dosti Vihar Pokhran Road,One can find this stunning 2 BHK flat for sale...,98.0,13799.0,thane,473.0,3 out of 22,Resale,Semi-Furnished,East,...,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,2.0,Pokhran Road,sqft,NaN
2,Sunrise by Kalpataru Kolshet Road,Up for immediate sale is a 2 BHK apartment in ...,140.0,17500.0,thane,779.0,10 out of 29,Resale,Unfurnished,East,...,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,2.0,Kolshet Road,sqft,NaN
3,Kasheli,This beautiful 1 BHK Flat is available for sal...,25.0,NaN,thane,530.0,1 out of 3,Resale,Unfurnished,NaN,...,NaN,1,1,NaN,NaN,NaN,1.0,Kasheli,sqft,NaN
4,TenX Habitat Raymond Realty Pokhran Road,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",160.0,18824.0,thane,635.0,20 out of 42,Resale,Unfurnished,West,...,TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,2.0,Pokhran Road,sqft,NaN

In [1642]:
def unit_standardization(col1, col2, units, values):
    for unit, value in zip(units, values):
        mask = house_copy[col2].str.contains(unit, na= False)
        house_copy.loc[mask, col1] = house_copy.loc[mask, col1] * value

units= ['sqyrd', 'sqm', 'marla', 'acre', 'kanal', 'ground', 'bigha', 'cent']    
carpet_values= [9, 10.764, 272.25, 43560, 5445, 2400, 6806.25, 435.6]
super_values= [9, 10.764, 272.25, 5445, 2400, 340.3125, 72, 43560, 107639.104, 435.6]

unit_standardization('carpet_area', 'carpet_unit', house_copy['carpet_unit'].value_counts().index[1:], carpet_values)
unit_standardization('super_area', 'super_unit', house_copy['super_unit'].value_counts().index[1:], super_values)

In [1643]:
house_copy.drop(columns= ['carpet_unit', 'super_unit'], inplace= True)

In [1644]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        68192 non-null  object
 1   description  65974 non-null  str
 2   amount       67841 non-null  float64
 3   price        62298 non-null  float64
 4   location     68192 non-null  str
 5   carpet_area  38075 non-null  float64
 6   floor        65577 non-null  str
 7   transaction  68114 non-null  str
 8   furnishing   66902 non-null  str
 9   facing       41392 non-null  str
 10  overlooking  38657 non-null  str
 11  society      29372 non-null  str
 12  bathroom     67721 non-null  str
 13  balcony      49133 non-null  str
 14  car_parking  28863 non-null  str
 15  ownership    43264 non-null  str
 16  super_area   29945 non-null  float64
 17  bedrooms     67831 non-null  float64
 18  locality     14607 non-null  str
dtypes: float64(5), object(1), str(13)
memory usage: 10.4+ MB

In [1645]:
mask = house_copy['price'].isna() & (house_copy['amount'].isna() == False) & (house_copy['super_area'].isna() == False)
house_copy.loc[mask, 'price'] = house_copy.loc[mask, 'amount'] / house_copy.loc[mask, 'super_area']

In [1646]:
mask = (house_copy['amount'].isna() == False) & (house_copy['price'].isna() == False) & (house_copy['super_area'].isna())
house_copy.loc[mask, 'super_area'] = (house_copy.loc[mask, 'amount'] * 100000) / house_copy.loc[mask, 'price']

In [1647]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        68192 non-null  object
 1   description  65974 non-null  str
 2   amount       67841 non-null  float64
 3   price        63575 non-null  float64
 4   location     68192 non-null  str
 5   carpet_area  38075 non-null  float64
 6   floor        65577 non-null  str
 7   transaction  68114 non-null  str
 8   furnishing   66902 non-null  str
 9   facing       41392 non-null  str
 10  overlooking  38657 non-null  str
 11  society      29372 non-null  str
 12  bathroom     67721 non-null  str
 13  balcony      49133 non-null  str
 14  car_parking  28863 non-null  str
 15  ownership    43264 non-null  str
 16  super_area   63766 non-null  float64
 17  bedrooms     67831 non-null  float64
 18  locality     14607 non-null  str
dtypes: float64(5), object(1), str(13)
memory usage: 10.4+ MB

In [1648]:
floor_data = house_copy['floor'].str.split(' out of ')
house_copy['floor'] = floor_data.str.get(0)
house_copy['total_floors'] = floor_data.str.get(1)

In [1649]:
house_copy['furnishing'].value_counts()

furnishing
Semi-Furnished    29248
Unfurnished       28537
Furnished          9117
Name: count, dtype: int64

In [1650]:
house_copy['furnishing_copy'] = house_copy['description'].str.extract(r'([A-Za-z\-]*(?:Furnished|furnished))')

In [1651]:
house_copy['furnishing_copy'].value_counts()

furnishing_copy
semi-furnished          28086
unfurnished             25967
furnished                8696
Furnished                  22
Unfurnished                16
FloorSemifurnished          6
semifurnished               5
Semi-Furnished              5
FloorsUnfurnished           4
Semifurnished               4
SqftUnfurnished             3
FloorUnfurnished            2
Semi-furnished              1
BalconyUnfurnished          1
well-furnished              1
fully-furnished             1
AvailableUnfurnished        1
SemiFurnished               1
Name: count, dtype: int64

In [1652]:
house_copy['furnishing_copy'] = np.where(house_copy['furnishing_copy'].str.contains(r'[Uu]n'), 'Unfurnished', house_copy['furnishing_copy'])
house_copy['furnishing_copy'] = np.where(house_copy['furnishing_copy'].str.contains(r'[Ss]emi'), 'Semi-Furnished', house_copy['furnishing_copy'])
house_copy['furnishing_copy'] = np.where(house_copy['furnishing_copy'].str.contains(r'[Uu]n|[Ss]emi') == False, 'Furnished', house_copy['furnishing_copy'])

In [1653]:
house_copy['furnishing'] = np.where(house_copy['furnishing'].isna(), house_copy['furnishing_copy'], house_copy['furnishing'])

In [1654]:
house_copy.drop(columns= 'furnishing_copy', inplace= True)

In [1655]:
house_copy['furnishing']= house_copy['furnishing'].astype('category')

In [1656]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         68192 non-null  object
 1   description   65974 non-null  str
 2   amount        67841 non-null  float64
 3   price         63575 non-null  float64
 4   location      68192 non-null  str
 5   carpet_area   38075 non-null  float64
 6   floor         65577 non-null  object
 7   transaction   68114 non-null  str
 8   furnishing    68192 non-null  category
 9   facing        41392 non-null  str
 10  overlooking   38657 non-null  str
 11  society       29372 non-null  str
 12  bathroom      67721 non-null  str
 13  balcony       49133 non-null  str
 14  car_parking   28863 non-null  str
 15  ownership     43264 non-null  str
 16  super_area    63766 non-null  float64
 17  bedrooms      67831 non-null  float64
 18  locality      14607 non-null  str
 19  total_floors  65529 non-null  object
dtypes: category(1), float64(5), object(3), str(11)
memory usage: 10.5+ MB

In [1657]:
house_copy['bathroom'].value_counts()
house_copy['balcony'].value_counts()

balcony
2       18755
1       15866
3       10169
4        3422
5         737
6         126
> 10       18
7          13
8          13
10         12
9           2
Name: count, dtype: int64

In [1658]:
house_copy['bathroom'] = house_copy['bathroom'].str.replace('> 10', '11').astype('float64')
house_copy['balcony'] = house_copy['balcony'].str.replace('> 10', '11').astype('float64')

In [1659]:
house_copy['transaction'].value_counts()
house_copy['ownership'].value_counts()

ownership
Freehold                37341
Leasehold                3070
Co-operative Society     2370
Power Of Attorney         483
Name: count, dtype: int64

In [1660]:
house_copy['transaction'] = house_copy['transaction'].astype('category')
house_copy['ownership'] = house_copy['ownership'].astype('category')

In [1661]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         68192 non-null  object
 1   description   65974 non-null  str
 2   amount        67841 non-null  float64
 3   price         63575 non-null  float64
 4   location      68192 non-null  str
 5   carpet_area   38075 non-null  float64
 6   floor         65577 non-null  object
 7   transaction   68114 non-null  category
 8   furnishing    68192 non-null  category
 9   facing        41392 non-null  str
 10  overlooking   38657 non-null  str
 11  society       29372 non-null  str
 12  bathroom      67721 non-null  float64
 13  balcony       49133 non-null  float64
 14  car_parking   28863 non-null  str
 15  ownership     43264 non-null  category
 16  super_area    63766 non-null  float64
 17  bedrooms      67831 non-null  float64
 18  locality      14607 non-null  str
 19  total_floors  65529 non-null  object
dtypes: category(3), float64(7), object(3), str(7)
memory usage: 9.6+ MB

In [1662]:
house_copy['overlooking'].value_counts()

overlooking
Main Road                                      12245
Garden/Park, Main Road                          8875
Garden/Park                                     8269
Garden/Park, Pool, Main Road                    4735
Pool, Garden/Park, Main Road                    1593
Garden/Park, Pool                               1383
Pool, Garden/Park                                367
Pool                                             355
Main Road, Garden/Park                           351
Main Road, Garden/Park, Pool                     213
Pool, Main Road                                  202
Garden/Park, Main Road, Pool                      37
Main Road, Pool                                   11
Main Road, Pool, Garden/Park                       8
Pool, Main Road, Garden/Park                       6
Main Road, Not Available                           4
Garden/Park, Pool, Main Road, Not Available        1
Garden/Park, Not Available                         1
Pool, Main Road, Not Available                     1
Name: count, dtype: int64

In [1663]:
mask = house_copy['overlooking'].isna() == False

def strip_advance(l):
    if l is np.nan:
        return np.nan
    for idx, i in enumerate(l):
        l[idx] = i.strip()
    return ",".join(sorted(l)).replace(r',Not Available', '')

house_copy['overlooking'] = house_copy.loc[mask, 'overlooking'].str.split(',').apply(strip_advance)

In [1664]:
house_copy['overlooking'] = house_copy['overlooking'].astype('category')

In [1665]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         68192 non-null  object
 1   description   65974 non-null  str
 2   amount        67841 non-null  float64
 3   price         63575 non-null  float64
 4   location      68192 non-null  str
 5   carpet_area   38075 non-null  float64
 6   floor         65577 non-null  object
 7   transaction   68114 non-null  category
 8   furnishing    68192 non-null  category
 9   facing        41392 non-null  str
 10  overlooking   38657 non-null  category
 11  society       29372 non-null  str
 12  bathroom      67721 non-null  float64
 13  balcony       49133 non-null  float64
 14  car_parking   28863 non-null  str
 15  ownership     43264 non-null  category
 16  super_area    63766 non-null  float64
 17  bedrooms      67831 non-null  float64
 18  locality      14607 non-null  str
 19  total_floors  65529 non-null  object
dtypes: category(4), float64(7), object(3), str(6)
memory usage: 9.1+ MB

In [1666]:
house_copy['car_parking'].value_counts()

car_parking
1 Covered      15781
1 Covered,      4103
1 Open          3441
2 Covered       2981
2 Covered,       875
               ...
104 Covered        1
205 Covered        1
11 Covered,        1
403 Covered        1
702 Open           1
Name: count, Length: 229, dtype: int64

In [ ]:
house_copy['car_parking_status'] = house_copy['car_parking'].str.extract(r'([Cc]overed|[Oo]pen)')
house_copy['car_parking'] = house_copy['car_parking'].str.extract(r'(\d+)')

car_parking
1      23325
2       4228
3        528
4        152
5         66
       ...
125        1
304        1
207        1
206        1
104        1
Name: count, Length: 156, dtype: int64

In [1668]:
house_copy['car_parking'] = house_copy['car_parking'].astype('float')
house_copy['car_parking_status'] = house_copy['car_parking_status'].astype('category')

In [1669]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               68192 non-null  object
 1   description         65974 non-null  str
 2   amount              67841 non-null  float64
 3   price               63575 non-null  float64
 4   location            68192 non-null  str
 5   carpet_area         38075 non-null  float64
 6   floor               65577 non-null  object
 7   transaction         68114 non-null  category
 8   furnishing          68192 non-null  category
 9   facing              41392 non-null  str
 10  overlooking         38657 non-null  category
 11  society             29372 non-null  str
 12  bathroom            67721 non-null  float64
 13  balcony             49133 non-null  float64
 14  car_parking         28863 non-null  float64
 15  ownership           43264 non-null  category
 16  super_area          63766 non-null  float64
 17  bedrooms            67831 non-null  float64
 18  locality            14607 non-null  str
 19  total_floors        65529 non-null  object
 20  car_parking_status  28863 non-null  category
dtypes: category(5), float64(8), object(3), str(5)
memory usage: 9.2+ MB

In [1674]:
house_copy['facing'] = house_copy['facing'].astype('category')
house_copy['location'] = house_copy['location'].astype('category')

In [1675]:
house_copy.info()

<class 'pandas.DataFrame'>
Index: 68192 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               68192 non-null  object
 1   description         65974 non-null  str
 2   amount              67841 non-null  float64
 3   price               63575 non-null  float64
 4   location            68192 non-null  category
 5   carpet_area         38075 non-null  float64
 6   floor               65577 non-null  object
 7   transaction         68114 non-null  category
 8   furnishing          68192 non-null  category
 9   facing              41392 non-null  category
 10  overlooking         38657 non-null  category
 11  society             29372 non-null  str
 12  bathroom            67721 non-null  float64
 13  balcony             49133 non-null  float64
 14  car_parking         28863 non-null  float64
 15  ownership           43264 non-null  category
 16  super_area          63766 non-null  float64
 17  bedrooms            67831 non-null  float64
 18  locality            14607 non-null  str
 19  total_floors        65529 non-null  object
 20  car_parking_status  28863 non-null  category
dtypes: category(7), float64(8), object(3), str(3)
memory usage: 8.3+ MB